apiVersion: v1
kind: Pod
metadata:
  name: mern-backend
  labels:
    app: mern-backend
spec:
  containers:
  - name: backend
    image: mern-backend:latest
    imagePullPolicy: Never
    ports:
    - containerPort: 8000
    env:
    - name: NODE_ENV
      value: "production"
    - name: MONGO_URI
      value: "mongodb+srv://sohilkhan612000_db_user:SNxTYbEepUHhFO1P@cluster0.0rav3ah.mongodb.net/interns?retryWrites=true&w=majority"
    - name: JWT_SECRET
      value: "843uitjkgdu879578rtjjkdfdfjkmcvxkjdfjwqxhksdkl"