# Use official MongoDB image
FROM mongo:7-jammy

# Set environment variables
ENV MONGO_INITDB_ROOT_USERNAME=admin
ENV MONGO_INITDB_ROOT_PASSWORD=password
ENV MONGO_INITDB_DATABASE=interns

# Expose MongoDB port
EXPOSE 27017

# Default command
CMD ["mongod"]