apiVersion: apps/v1
kind: Deployment
metadata:
  name: mern-frontend
spec:
  replicas: 3   # You can change this based on your need
  selector:
    matchLabels:
      app: mern-frontend
  template:
    metadata:
      labels:
        app: mern-frontend
    spec:
      containers:
        - name: frontend
          image: eightbitsystem3/mern-frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
