apiVersion: v1
kind: Pod
metadata:
  name: mern-frontend
  labels:
    app: mern-frontend
spec:
  containers:
    - name: frontend
      image: mern-frontend:latest
      imagePullPolicy: Never
      ports:
        - containerPort: 3000