apiVersion: apps/v1
kind: Deployment
metadata:
  name: mern-frontend
  namespace: mern
spec:
  replicas: 3   # You can change this based on your need
  selector:
    matchLabels:
      app: mern-frontend
  template:
    metadata:
      labels:
        app: mern-frontend
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .Values.containerPort }}
