apiVersion: v1
kind: Service
metadata:
  name: {{ include "mern-frontend.fullname" . }}
  namespace: mern
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "mern-frontend.name" . }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort }}
      nodePort: {{ .Values.service.nodePort }}
