apiVersion: v1
kind: Service
metadata:
  name: mern-backend
  namespace: default
spec:
  type: NodePort
  selector:
    app: mern-backend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30008